[package]
name = "chip8rust"
version = "0.1.0"
edition = "2021"
 
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pixels = "0.13.0"
rusttype = "0.9.3"
sdl2 = "0.35.2"
softbuffer = "0.3.1"
winit = "0.28.5"

