pub enum Instruction {
    ClearScreen,
    FillScreen,
    Jump { addr: u16},
    CallSubroutine { addr: u16},
    ReturnSubroutine,
    Set { register: usize, value: u8},
    Add { register: usize, value: u8},
    SetI { value: u16 },
    DisplayDraw { register_x: u8, register_y: u8, n: u8},
    BinaryOrVX { register_x: u8, register_y: u8},
    BinaryAndVX { register_x: u8, register_y: u8},
    BinaryXorVX { register_x: u8, register_y: u8},
    AddVX { register_x: u8, register_y: u8},
    Nop,
    SkipIfEqual { register_x: usize, value: u8 },
    SkipIfNotEqual { register_x: usize, value: u8 },
    SkipIfRegistersEqual { register_x: usize, register_y: usize },
    SkipIfRegistersNotEqual { register_x: usize, register_y: usize },
    SubstractVXVY {register_x: usize, register_y: usize},
    SubstractVYVX {register_x: usize, register_y: usize},
    ShiftLeft {register_x: usize, register_y: usize},
    ShiftRight {register_x: usize, register_y: usize},
    AddI { register_x: usize},
    SkipIfKeyPressed { keycode: u8},
    SkipIfKeyNotPressed { keycode: u8},
}